package me.fexus.vulkan.component.pipeline.pipelinestage

import org.lwjgl.vulkan.VK12.*


enum class PipelineStage(override val vkBits: Int): IPipelineStage {
    TOP_OF_PIPE(VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT),
    VERTEX_INPUT(VK_PIPELINE_STAGE_VERTEX_INPUT_BIT),
    VERTEX_SHADER(VK_PIPELINE_STAGE_VERTEX_SHADER_BIT),
    GEOMETRY_SHADER(VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT),
    FRAGMENT_SHADER(VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT),
    COLOR_ATTACHMENT_OUTPUT(VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT),
    COMPUTE(VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT),
    TRANSFER(VK_PIPELINE_STAGE_TRANSFER_BIT),
    BOTTOM_OF_PIPE(VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT)
}