#define INPUT_FORWARD_BIT 1
#define INPUT_BACKWARD_BIT 2
#define INPUT_LEFT_BIT 4
#define INPUT_RIGHT_BIT 8
#define INPUT_SLOW_BIT 16
#define INPUT_SHOOT_BIT 32
#define INPUT_SPELL_BIT 64
#define INPUT_PAUSE_BIT 128
