package me.fexus.vulkan.descriptors.buffer.usage

import org.lwjgl.vulkan.KHRAccelerationStructure.VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR
import org.lwjgl.vulkan.KHRAccelerationStructure.VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR
import org.lwjgl.vulkan.VK12


enum class BufferUsage(override val vkBits: Int): IBufferUsage {
    STORAGE_BUFFER(VK12.VK_BUFFER_USAGE_STORAGE_BUFFER_BIT),
    UNIFORM_BUFFER(VK12.VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT),
    VERTEX_BUFFER(VK12.VK_BUFFER_USAGE_VERTEX_BUFFER_BIT),
    INDEX_BUFFER(VK12.VK_BUFFER_USAGE_INDEX_BUFFER_BIT),
    TRANSFER_DST(VK12.VK_BUFFER_USAGE_TRANSFER_DST_BIT),
    TRANSFER_SRC(VK12.VK_BUFFER_USAGE_TRANSFER_SRC_BIT),
    INDIRECT(VK12.VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT),
    ACCELERATION_STRUCTURE_STORAGE_KHR(VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR),
    ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_KHR(VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR),
    SHADER_DEVICE_ADDRESS(VK12.VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT)
}